source env/bin/activate
python src/cnntorch.py --sub "sub-01"
python src/cnntorch.py --sub "sub-02"
python src/cnntorch.py --sub "sub-03"
python src/cnntorch.py --sub "sub-04"
python src/cnntorch.py --sub "sub-05"
python src/cnntorch.py --sub "sub-06"
python src/cnntorch.py --sub "sub-07"
python src/cnntorch.py --sub "sub-08"
python src/cnntorch.py --sub "sub-09"
python src/cnntorch.py --sub "sub-10"
python src/cnntorch.py --sub "sub-11"
python src/cnntorch.py --sub "sub-12"
python src/cnntorch.py --sub "sub-13"
python src/cnntorch.py --sub "sub-14"
python src/cnntorch.py --sub "sub-15"
python src/cnntorch.py --sub "sub-16"